#!/usr/bin/env python3
"""Build-time music converter for the Nintendo N64 port.

Reconstructs `ports/SDL2`'s `MusicPlayer.levelGroups` (main.swift) - 5 short,
loopable musical phrases (`audio/music/lego1.*.ogg`, `demo_4.*.ogg`, etc.),
one of which is picked at random per level - but simplified for v1: no
multi-track shuffling within a group and no fade-out "end" sting, just one
track per group played on an infinite hardware loop
(`soundPlaySample(...,loop:true)`, which needs no per-frame CPU attention
once started, unlike real streaming). The title-screen-only `intro_1.*`
clips are skipped since this v1 port has no separate title screen.

Every clip embeds directly into the ARM9 binary (same approach as
tools/gen_audio.py's sound effects), so - unlike a real streaming player -
total music size is bounded by the N64.s ~4MB whole-ELF RDRAM budget alongside
everything else. That budget is why these are downsampled to 8kHz (half the
source 16kHz): at native rate the 5 groups' tracks alone are ~716KB, which
didn't fit; 8kHz halves that to ~358KB for a barely-noticeable quality loss
on music this short and already lo-fi.

Emits:
  <out>/music.bin        -- every group's candidate tracks, concatenated;
                             the N64 binary picks one track per group at
                             runtime (see source/Audio.swift).
  <out>/MusicAssets.swift -- per-group array of (offset, length) clip
                             descriptors, sample rate 8000 for all.

Usage: gen_music.py <repo_root> <out_dir>
"""

import subprocess
import sys
import tempfile
import wave
from pathlib import Path

TARGET_RATE = 8000

# Mirrors ports/SDL2/Sources/JunkbotSDL2/main.swift's MusicPlayer.levelGroups,
# minus each group's "end" sting (skipped for v1 - see module docstring).
GROUPS = [
    ("lego1", ["lego1.1", "lego1.2", "lego1.3"]),
    ("demo_4", ["demo_4.1", "demo_4.3", "demo_4.5", "demo_4.6"]),
    ("demo_5", ["demo_5.1", "demo_5.2", "demo_5.7", "demo_5.8"]),
    ("demo_6", ["demo_6.1", "demo_6.2", "demo_6.4", "demo_6.5"]),
    ("demo6", ["demo6_3", "demo6_5", "demo6_6"]),
]


def decode_to_pcm8_mono(path, tmpdir, rate):
    wav_path = tmpdir / (path.stem + ".wav")
    subprocess.run(
        ["afconvert", "-f", "WAVE", "-d", f"LEI16@{rate}", "-c", "1", str(path), str(wav_path)],
        check=True, capture_output=True)
    with wave.open(str(wav_path), "rb") as w:
        assert w.getnchannels() == 1 and w.getsampwidth() == 2 and w.getframerate() == rate
        raw = w.readframes(w.getnframes())
    # Signed 16-bit -> signed 8-bit: arithmetic shift (drop the low byte),
    # matching tools/gen_audio.py's sound-effect conversion exactly.
    pcm8 = bytearray(len(raw) // 2)
    for i in range(len(pcm8)):
        v = raw[2 * i + 1]  # high byte of each little-endian int16 sample
        pcm8[i] = v
    return bytes(pcm8)


def main():
    if len(sys.argv) != 3:
        raise SystemExit("usage: gen_music.py <repo_root> <out_dir>")
    repo_root = Path(sys.argv[1]).resolve()
    out_dir = Path(sys.argv[2]).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    music_dir = repo_root / "audio/music"

    blob = bytearray()
    group_swift_entries = []
    total_clips = 0
    with tempfile.TemporaryDirectory() as tmp:
        tmpdir = Path(tmp)
        for group_name, tracks in GROUPS:
            clip_entries = []
            for track in tracks:
                src = music_dir / f"{track}.ogg"
                if not src.exists():
                    print(f"warning: missing music track {src}", file=sys.stderr)
                    continue
                pcm8 = decode_to_pcm8_mono(src, tmpdir, TARGET_RATE)
                clip_entries.append((len(blob), len(pcm8)))
                blob += pcm8
                total_clips += 1
            entries_literal = ", ".join(
                f"(offset: {offset}, length: {length})" for offset, length in clip_entries)
            group_swift_entries.append(f"  [{entries_literal}],  // {group_name}")

    (out_dir / "music.bin").write_bytes(blob)
    body = "\n".join(group_swift_entries)
    (out_dir / "MusicAssets.swift").write_text(
        "// Generated by ports/N64/tools/gen_music.py - do not edit.\n"
        "\n"
        "/// One randomly-picked-at-level-load group of loopable background clips (byte\n"
        "/// offset/length within `music.bin`, all at 8kHz signed 8-bit PCM mono) -\n"
        "/// mirrors ports/SDL2's 5 `MusicPlayer.levelGroups`, minus per-group track\n"
        "/// shuffling and the fade-out \"end\" sting (see gen_music.py).\n"
        "let musicGroupSampleRate: Int32 = 8000\n"
        "let musicGroups: [[(offset: Int32, length: Int32)]] = [\n"
        f"{body}\n"
        "]\n"
    )
    print(f"music.bin: {total_clips} clips across {len(GROUPS)} groups, "
          f"{len(blob)} bytes ({len(blob) / 1024:.1f} KB)")


if __name__ == "__main__":
    main()
