#!/usr/bin/env python3
"""Generates Sources/JunkbotCore/Generated/{SpriteTable,JunkbotKeyframes}.swift from the sprite
atlas JSONs and junkbot-animations.json.

The generated files give every atlas frame name a stable Int32 "sprite ID" (an index into
parallel name/sheet tables) so the render-command emitter in JunkbotCore (RenderList.swift) can
identify sprites by pure integer arithmetic - `familyBase + frameNumber` - with no String
operations or Dictionary lookups in the per-frame path (an embedded-Swift-WASM requirement; see
the "Embedded Swift" notes in the repo's plan file).

ID layout: sheets in fixed order (sprites, spritesUndercover, backgrounds,
backgroundsUndercover); within each sheet, frame families (names matching `^(.*)_(\\d+)$`,
e.g. minifig_walk_l_1..10) as contiguous blocks sorted by family name, then singleton names
sorted. A family's block covers its full [minFrame...maxFrame] range so `base + frame` always
lands inside the block even for families with gaps (brick_* skips widths 5 and 7); gap slots get
an empty name and are invalid to draw.

Run via `make codegen` after changing any atlas JSON or junkbot-animations.json, and commit the
regenerated files. RenderListTests pins spot IDs to catch uncommitted drift.
"""

import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

SHEETS = [
    # (swift case name, sheet index, atlas path, constant prefix)
    ("sprites", 0, "images/spritesheets/sprites.json", ""),
    ("spritesUndercover", 1, "images/spritesheets/Undercover Exclusive/sprites.json", ""),
    ("backgrounds", 2, "images/spritesheets/backgrounds.json", "bg_"),
    ("backgroundsUndercover", 3, "images/spritesheets/Undercover Exclusive/backgrounds.json", "bgU_"),
]

FAMILY_RE = re.compile(r"^(.*)_(\d+)$")


def camel(name: str) -> str:
    """brick_blue -> brickBlue; HAZ_SLICKCRATE -> hazSlickcrate; fanAir_1 -> fanAir1."""
    parts = name.replace("-", "_").split("_")
    out = []
    for i, part in enumerate(parts):
        if not part:
            continue
        if part.isupper():
            part = part.capitalize()
        if i == 0:
            part = part[0].lower() + part[1:]
        else:
            part = part[0].upper() + part[1:]
        out.append(part)
    ident = "".join(out)
    if ident[0].isdigit():
        ident = "_" + ident
    return ident


def main() -> None:
    entries = []  # (name or "" for gap, sheet_index, width, height)
    family_consts = []  # (identifier, base, min_frame, max_frame)
    singleton_consts = []  # (identifier, id)

    for _, sheet_index, atlas_path, prefix in SHEETS:
        with open(REPO / atlas_path) as f:
            atlas = json.load(f)
        # name -> (width, height) from the atlas frame bounds [left, top, w, h]. These are the
        # authoritative on-screen sizes (JS draws src AND dest at atlas size), letting the
        # emitter compute exact draw positions without backends supplying texture dimensions.
        size_by_name = {}
        for raw_name, frame_indices in atlas["animations"].items():
            name = re.sub(r"\.png$", "", raw_name, flags=re.I)
            _, _, w, h = atlas["frames"][frame_indices[0]]
            size_by_name[name] = (w, h)

        families: dict[str, list[int]] = {}
        singletons: list[str] = []
        for name in size_by_name:
            m = FAMILY_RE.match(name)
            if m:
                families.setdefault(m.group(1), []).append(int(m.group(2)))
            else:
                singletons.append(name)

        def add_entry(name: str) -> None:
            w, h = size_by_name.get(name, (0, 0))
            entries.append((name, sheet_index, w, h))

        for family in sorted(families):
            frames = sorted(families[family])
            lo, hi = frames[0], frames[-1]
            frame_set = set(frames)
            block_start = len(entries)
            for frame in range(lo, hi + 1):
                add_entry(f"{family}_{frame}" if frame in frame_set else "")
            # base such that ID == base + frameNumber
            family_consts.append((camel(prefix + family), block_start - lo, lo, hi))

        for name in sorted(singletons):
            singleton_consts.append((camel(prefix + name), len(entries)))
            add_entry(name)

    # Collision check across all generated constant identifiers.
    idents = [c[0] for c in family_consts] + [c[0] for c in singleton_consts]
    dupes = {i for i in idents if idents.count(i) > 1}
    if dupes:
        sys.exit(f"generated identifier collision(s): {sorted(dupes)}")

    generated_by = "tools/generate_render_tables.py - do not edit by hand; run `make codegen`."

    sprite_table = [f"// Generated by {generated_by}", ""]
    sprite_table.append("/// Which source image a sprite ID's frame lives in. Raw values cross the JS bridge.")
    sprite_table.append("public enum SpriteSheet: Int32 {")
    for case_name, sheet_index, _, _ in SHEETS:
        sprite_table.append(f"  case {case_name} = {sheet_index}")
    sprite_table.append("}")
    sprite_table.append("")
    sprite_table.append("/// Atlas frame name for each sprite ID (empty string = unused gap slot in a family with")
    sprite_table.append("/// non-contiguous frame numbers, e.g. brick widths 5/7). Index = sprite ID.")
    sprite_table.append("public let spriteNameTable: [StaticString] = [")
    for name, _, _, _ in entries:
        sprite_table.append(f'  "{name}",')
    sprite_table.append("]")
    sprite_table.append("")
    sprite_table.append("/// SpriteSheet.rawValue for each sprite ID. Index = sprite ID.")
    sprite_table.append("public let spriteSheetTable: [Int32] = [")
    for _, sheet_index, _, _ in entries:
        sprite_table.append(f"  {sheet_index},")
    sprite_table.append("]")
    sprite_table.append("")
    sprite_table.append("/// On-screen pixel size of each sprite ID's frame (from the atlas bounds - the")
    sprite_table.append("/// authoritative render size; JS draws source and destination at exactly this size).")
    sprite_table.append("public let spriteWidthTable: [Int32] = [")
    for _, _, w, _ in entries:
        sprite_table.append(f"  {w},")
    sprite_table.append("]")
    sprite_table.append("")
    sprite_table.append("public let spriteHeightTable: [Int32] = [")
    for _, _, _, h in entries:
        sprite_table.append(f"  {h},")
    sprite_table.append("]")
    sprite_table.append("")
    sprite_table.append("/// Namespaced sprite ID constants. For frame families, `ID == <family>Base + frameNumber`")
    sprite_table.append("/// (frame numbers as they appear in the atlas names, NOT zero-based - most start at 1).")
    sprite_table.append("public enum SpriteID {")
    for ident, base, lo, hi in family_consts:
        sprite_table.append(f"  public static let {ident}Base: Int32 = {base}  // frames {lo}...{hi}")
        sprite_table.append(f"  public static let {ident}Count: Int32 = {hi - lo + 1}")
    for ident, sprite_id in singleton_consts:
        sprite_table.append(f"  public static let {ident}: Int32 = {sprite_id}")
    sprite_table.append("}")
    sprite_table.append("")

    out_dir = REPO / "Sources/JunkbotCore/Generated"
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "SpriteTable.swift").write_text("\n".join(sprite_table))

    # Junkbot walk-cycle keyframes, names pre-resolved to sprite IDs.
    id_by_name_sheet0 = {name: i for i, (name, sheet, _, _) in enumerate(entries) if sheet == 0 and name}
    with open(REPO / "junkbot-animations.json") as f:
        anims = json.load(f)

    keyframes = [f"// Generated by {generated_by}", ""]
    keyframes.append("/// One keyframe of a Junkbot walk-cycle animation (from junkbot-animations.json): the")
    keyframes.append("/// sprite to show and its pixel offset from Junkbot's base draw position. Same data")
    keyframes.append("/// src/game.js loads at runtime as resources.junkbotAnimations, with sprite names")
    keyframes.append("/// pre-resolved to sprite IDs at generation time.")
    keyframes.append("public struct JunkbotKeyframe: Sendable {")
    keyframes.append("  public let spriteID: Int32")
    keyframes.append("  public let dx: Int32")
    keyframes.append("  public let dy: Int32")
    keyframes.append("}")
    keyframes.append("")
    for anim_name in sorted(anims):
        frames = anims[anim_name]
        keyframes.append(f"public let junkbotAnim_{anim_name}: [JunkbotKeyframe] = [")
        for kf in frames:
            sprite = kf["sprite"]
            if sprite not in id_by_name_sheet0:
                sys.exit(f"junkbot-animations.json references unknown sprite: {sprite}")
            off = kf["offset"]
            keyframes.append(
                f"  JunkbotKeyframe(spriteID: {id_by_name_sheet0[sprite]}, dx: {off['x']}, dy: {off['y']}),"
            )
        keyframes.append("]")
        keyframes.append("")

    (out_dir / "JunkbotKeyframes.swift").write_text("\n".join(keyframes))
    print(f"Wrote {len(entries)} sprite IDs ({len(family_consts)} families, "
          f"{len(singleton_consts)} singletons) and {len(anims)} junkbot animations.")


if __name__ == "__main__":
    main()
