#!/usr/bin/env python3
"""Build-time music converter for the Nintendo 3DS port.

Reconstructs `ports/SDL2`'s `MusicPlayer.levelGroups` (main.swift) - 5 short,
loopable musical phrases (`audio/music/lego1.*.ogg`, `demo_4.*.ogg`, etc.),
one of which is picked at random per level - simplified for v1 like
ports/NDS: no multi-track shuffling within a group and no fade-out "end"
sting, just one track per group played on an infinite hardware loop
(`ndspWaveBuf.looping`). Unlike the DS port, tracks are kept at native sample
rate and 16-bit PCM (no downsampling needed -- the 3DS has plenty of RAM).
The title-screen-only `intro_1.*` clips are skipped since this v1 port has no
separate title screen.

Emits:
  <out>/music.bin        -- every group's candidate tracks, concatenated;
                             the 3DS binary picks one track per group at
                             runtime (see source/Audio.swift).
  <out>/MusicAssets.swift -- per-group array of (offset, length, sampleRate)
                             clip descriptors, in bytes.

Usage: gen_music.py <repo_root> <out_dir>
"""

import subprocess
import struct
import sys
import tempfile
import wave
from pathlib import Path

# Mirrors ports/SDL2/Sources/JunkbotSDL2/main.swift's MusicPlayer.levelGroups,
# minus each group's "end" sting (skipped for v1 - see module docstring).
GROUPS = [
    ("lego1", ["lego1.1", "lego1.2", "lego1.3"]),
    ("demo_4", ["demo_4.1", "demo_4.3", "demo_4.5", "demo_4.6"]),
    ("demo_5", ["demo_5.1", "demo_5.2", "demo_5.7", "demo_5.8"]),
    ("demo_6", ["demo_6.1", "demo_6.2", "demo_6.4", "demo_6.5"]),
    ("demo6", ["demo6_3", "demo6_5", "demo6_6"]),
]


def decode_to_pcm16_mono(path, tmpdir):
    wav_path = tmpdir / (path.stem + ".wav")
    subprocess.run(
        ["afconvert", "-f", "WAVE", "-d", "LEI16", "-c", "1", str(path), str(wav_path)],
        check=True, capture_output=True)
    with wave.open(str(wav_path), "rb") as w:
        assert w.getnchannels() == 1 and w.getsampwidth() == 2
        rate = w.getframerate()
        raw = w.readframes(w.getnframes())
    return rate, raw


def main():
    if len(sys.argv) != 3:
        raise SystemExit("usage: gen_music.py <repo_root> <out_dir>")
    repo_root = Path(sys.argv[1]).resolve()
    out_dir = Path(sys.argv[2]).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    music_dir = repo_root / "audio/music"

    blob = bytearray()
    group_swift_entries = []
    total_clips = 0
    with tempfile.TemporaryDirectory() as tmp:
        tmpdir = Path(tmp)
        for group_name, tracks in GROUPS:
            clip_entries = []
            for track in tracks:
                src = music_dir / f"{track}.ogg"
                if not src.exists():
                    print(f"warning: missing music track {src}", file=sys.stderr)
                    continue
                rate, pcm16 = decode_to_pcm16_mono(src, tmpdir)
                clip_entries.append((len(blob), len(pcm16), rate))
                blob += pcm16
                total_clips += 1
            entries_literal = ", ".join(
                f"(offset: {offset}, length: {length}, sampleRate: {rate})"
                for offset, length, rate in clip_entries)
            group_swift_entries.append(f"  [{entries_literal}],  // {group_name}")

    (out_dir / "music.bin").write_bytes(blob)
    body = "\n".join(group_swift_entries)
    (out_dir / "MusicAssets.swift").write_text(
        "// Generated by ports/3DS/tools/gen_music.py - do not edit.\n"
        "\n"
        "/// One randomly-picked-at-level-load group of loopable background clips\n"
        "/// (byte offset/length/sample-rate within `music.bin`, signed 16-bit PCM\n"
        "/// mono) - mirrors ports/SDL2's 5 `MusicPlayer.levelGroups`, minus\n"
        "/// per-group track shuffling and the fade-out \"end\" sting (see gen_music.py).\n"
        "let musicGroups: [[(offset: Int32, length: Int32, sampleRate: Int32)]] = [\n"
        f"{body}\n"
        "]\n"
    )
    print(f"music.bin: {total_clips} clips across {len(GROUPS)} groups, "
          f"{len(blob)} bytes ({len(blob) / 1024:.1f} KB)")


if __name__ == "__main__":
    main()
