// Build-time level converter for the Nintendo DS port.
//
// The DS binary doesn't parse level text at runtime (the text parser needs
// full-Unicode String operations that are a poor fit for Embedded Swift).
// Instead, this host tool loads every campaign level through the REAL
// JunkbotCore parser + entity bridge (`GameEngine.loadLevel(fromText:)`) and
// emits the resulting entity lists as generated Swift, which the DS build
// compiles in and hands straight to `GameEngine.loadLevelState`.
//
// Each entity is reconstructed as `Entity(id:type:x:y:width:height:)` plus
// assignments for exactly the fields that differ from that initializer's
// defaults, discovered by reflecting (`Mirror`) both the loaded entity and a
// default-constructed twin -- so new Entity fields are picked up here
// automatically without touching this tool.
//
// Usage: swift run LevelDump <repo_root> <output.swift>

import Foundation
import JunkbotCore

guard CommandLine.arguments.count == 3 else {
  FileHandle.standardError.write(Data("usage: LevelDump <repo_root> <output.swift>\n".utf8))
  exit(2)
}
let repoRoot = URL(fileURLWithPath: CommandLine.arguments[1])
let outputPath = CommandLine.arguments[2]

func readLevelText(at url: URL) -> String? {
  guard var text = try? String(contentsOf: url, encoding: .utf8) else { return nil }
  if text.hasPrefix("\u{FEFF}") { text.removeFirst() }
  return text
}

/// `e.<label> = <literal>` lines for every stored property of `entity` that
/// differs from a freshly-initialized entity with the same id/type/geometry.
/// All Entity fields are Int32, Bool, or EntityType (handled by the init).
func fieldAssignments(for entity: Entity) -> [String] {
  let defaults = Entity(
    id: entity.id, type: entity.type, x: entity.x, y: entity.y,
    width: entity.width, height: entity.height)
  let entityMirror = Mirror(reflecting: entity)
  let defaultsMirror = Mirror(reflecting: defaults)
  var lines: [String] = []
  for (child, defaultChild) in zip(entityMirror.children, defaultsMirror.children) {
    guard let label = child.label else { continue }
    switch (child.value, defaultChild.value) {
    case (let value as Int32, let defaultValue as Int32):
      if value != defaultValue { lines.append("e.\(label) = \(value)") }
    case (let value as Bool, let defaultValue as Bool):
      if value != defaultValue { lines.append("e.\(label) = \(value)") }
    case (is EntityType, is EntityType):
      break  // covered by the initializer
    default:
      FileHandle.standardError.write(
        Data("error: Entity.\(label) has an unsupported type for LevelDump\n".utf8))
      exit(1)
    }
  }
  return lines
}

func swiftStringLiteral(_ s: String) -> String {
  var out = "\""
  for c in s.unicodeScalars {
    switch c {
    case "\\": out += "\\\\"
    case "\"": out += "\\\""
    case "\n": out += "\\n"
    case "\r": out += "\\r"
    case "\t": out += "\\t"
    default:
      // A couple of hint strings contain stray control bytes (e.g. 0x18 in
      // Number One Fan) that Swift source can't hold raw.
      if c.value < 0x20 || c.value == 0x7F {
        out += "\\u{\(String(c.value, radix: 16))}"
      } else {
        out.unicodeScalars.append(c)
      }
    }
  }
  return out + "\""
}

let catalog = LevelCatalog(repoRoot: repoRoot)
let entries = (catalog.pagesByGame[.junkbot] ?? []).flatMap { $0 }
guard !entries.isEmpty else {
  FileHandle.standardError.write(Data("error: no levels found under \(repoRoot.path)/levels\n".utf8))
  exit(1)
}

var output = """
  // Generated by ports/NDS/tools/LevelDump - do not edit.
  //
  // Every campaign level (levels/_LEVEL_LISTING.txt order), pre-parsed on the
  // host through JunkbotCore's own text parser + entity bridge and frozen as
  // entity-builder code. Load with:
  //   gameEngine.loadLevelState(entities: level.makeEntities(),
  //                             levelBounds: level.bounds, nextID: 0)
  //   gameEngine.setBackground(backdropSpriteID: level.backdropSpriteID,
  //                            backgroundDecals: [], decals: [])

  struct EmbeddedLevel {
    let title: StaticString
    let hint: StaticString
    /// Int32.max = no par declared.
    let par: Int32
    /// nil = the level declared no explicit playfield size (no boundary).
    let bounds: LevelBounds?
    let backdropSpriteID: Int32
    let makeEntities: () -> [Entity]
  }


  """

var levelLiterals: [String] = []
let engine = GameEngine()

for entry in entries {
  guard let text = readLevelText(at: entry.url) else {
    FileHandle.standardError.write(Data("error: unreadable \(entry.url.path)\n".utf8))
    exit(1)
  }
  let level = Level(text: text)
  engine.loadLevel(fromText: text)

  // `var e` is re-declared per entity; wrap each in a do-block scope.
  var builder = "{\n"
  builder += "      var entities: [Entity] = []\n"
  builder += "      entities.reserveCapacity(\(engine.entities.count))\n"
  for entity in engine.entities {
    builder += "      do {\n"
    builder +=
      "        var e = Entity(id: \(entity.id), type: EntityType(rawValue: \(entity.type.rawValue))!, "
      + "x: \(entity.x), y: \(entity.y), width: \(entity.width), height: \(entity.height))\n"
    let assignments = fieldAssignments(for: entity)
    if assignments.isEmpty {
      // Silence the unmutated-variable warning without a separate binding.
      builder += "        e.grabbed = false\n"
    }
    for line in assignments {
      builder += "        \(line)\n"
    }
    builder += "        entities.append(e)\n"
    builder += "      }\n"
  }
  builder += "      return entities\n"
  builder += "    }"

  let boundsLiteral: String
  if let bounds = engine.levelBounds {
    boundsLiteral =
      "LevelBounds(x: \(bounds.x), y: \(bounds.y), width: \(bounds.width), height: \(bounds.height))"
  } else {
    boundsLiteral = "nil"
  }
  let parLiteral = engine.levelPar == Int.max ? "Int32.max" : "\(engine.levelPar)"
  let backdropID = backgroundSpriteIDForName(level.background?.backdrop ?? "bkg1") ?? -1

  levelLiterals.append(
    """
      EmbeddedLevel(
        title: \(swiftStringLiteral(entry.title)),
        hint: \(swiftStringLiteral(engine.levelHint)),
        par: \(parLiteral),
        bounds: \(boundsLiteral),
        backdropSpriteID: \(backdropID),
        makeEntities: \(builder)),
    """)
}

output += "let embeddedLevels: [EmbeddedLevel] = [\n"
output += levelLiterals.joined(separator: "\n")
output += "\n]\n"

try output.write(toFile: outputPath, atomically: true, encoding: .utf8)
print("LevelDump: \(entries.count) levels -> \(outputPath)")
