name: Swift
on: [push]
jobs:

  macos:
    name: macOS
    runs-on: macos-26
    strategy:
      matrix:
        config: ["debug"]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Swift Version
      run: swift --version
    - name: Build
      run: swift build -c ${{ matrix.config }} --target JunkbotCore
    - name: Build Tests
      run: swift build -c ${{ matrix.config }} --product JunkbotPackageTests
    - name: Test
      run: swift test -c ${{ matrix.config }} --skip-build

  linux:
    name: Linux (${{ matrix.container }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container: ["swift:latest", "swiftlang/swift:nightly-noble"]
        config: ["debug"]
    container: ${{ matrix.container }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Swift Version
      run: swift --version
    - name: Build
      run: swift build -c ${{ matrix.config }} --target JunkbotCore
    - name: Build Tests
      run: swift build -c ${{ matrix.config }} --product JunkbotPackageTests
    - name: Test
      run: swift test -c ${{ matrix.config }} --skip-build
  
  android:
      name: Android
      strategy:
        fail-fast: false
        matrix:
          swift: ['6.3.2']
          arch: ["aarch64", "x86_64"]
      runs-on: macos-26
      timeout-minutes: 30
      steps:
        - uses: actions/checkout@v4
        - name: "Build Swift Package for Android"
          run: |
              brew install skiptools/skip/skip || (brew update && brew install skiptools/skip/skip)
              skip android sdk install --version ${{ matrix.swift }}
              ANDROID_NDK_ROOT="" skip android build --arch ${{ matrix.arch }} --target JunkbotCore
